# Generated by Django 5.1.6 on 2025-02-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_make',
            field=models.TextField(blank=True, verbose_name='Марка автомобиля'),
        ),
    ]
