# Generated by Django 5.1.6 on 2025-02-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_car_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_make',
            field=models.TextField(max_length=20, verbose_name='Марка автомобиля'),
        ),
    ]
